version: "3"

services:

  mysql:
    container_name: reference_mysql
    image: mysql:8.2.0
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    build:
        context: ./
        dockerfile: mysql.Dockerfile
    ports:
      - ${MYSQL_PORT}:3306
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    restart: always

    networks:
      - reference_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"



  rabbitmq:
    container_name: reference_rabbitmq
    build:
        context: ./
        dockerfile: rabbitmq.Dockerfile
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    networks:
      - reference_network

    volumes:
      - ${RABBITMQ_DATA_VOLUME}:/var/lib/rabbitmq
      - ${RABBITMQ_LOG_VOLUME}:/var/log/rabbitmq

    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

networks:
    reference_network:
        driver: bridge
